### ISSUE TITLE
Index page url for app

### ISSUE THREAD

**Issue by thevangelist** [Lepovirta/Crystallize#12]
Let's assume we use nginx...

Whats the best url? e.g.

`kiteyttaja.qatsi.info`
`qatsi.info/kiteyttaja`

Url should be chosen beforehand, so we might have some fiddling time if the url is sent along with the game packages at next week or so.

**Comment by keveri** [comment]
I think this is good: `kiteyttaja.qatsi.info`

**Comment by thevangelist** [comment]
Alright yeah, I am unsure do people trust "subdomain naming style", but let's assume that it's okay. I guess I should put a more relevant placeholder site for qatsi.info as well, if users check it?

**Comment by thevangelist** [comment]
`kiteyttaja.qatsi.info` it is.
