### ISSUE TITLE
Email sending to admin & customer

### ISSUE THREAD

**Issue by thevangelist** [Lepovirta/Crystallize#33]
...Would be nice, if user forgets to save the document

**Comment by keveri** [comment]
We will need some information for this:
- from email
- user & password
- host (SMTP server)

**Comment by keveri** [comment]
I got the email credentials.

**Comment by keveri** [comment]
PR #39 Added email sending to customer. It still saves the PDF as before. Should we also send some information in an email to the admin? For example the company name that used Kiteyttäjä.

**Comment by thevangelist** [comment]
I would send email with subject: "Kiteyttäjä - Uusi vastaus" once an answer has arrived, I'd also change the "Kiteyttäjä" subject for end users to be "Gälliwashere - Kiteyttäjän tulokset" or something.

**Comment by thevangelist** [comment]
We can have an improvement issue, closing this as the scope is filled.
